/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.dp.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MyKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MyKey\",\"namespace\":\"org.dp.avro\",\"fields\":[{\"name\":\"key\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence key;

  /**
   * Default constructor.
   */
  public MyKey() {}

  /**
   * All-args constructor.
   */
  public MyKey(java.lang.CharSequence key) {
    this.key = key;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return key;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: key = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'key' field.
   */
  public java.lang.CharSequence getKey() {
    return key;
  }

  /**
   * Sets the value of the 'key' field.
   * @param value the value to set.
   */
  public void setKey(java.lang.CharSequence value) {
    this.key = value;
  }

  /** Creates a new MyKey RecordBuilder */
  public static org.dp.avro.MyKey.Builder newBuilder() {
    return new org.dp.avro.MyKey.Builder();
  }
  
  /** Creates a new MyKey RecordBuilder by copying an existing Builder */
  public static org.dp.avro.MyKey.Builder newBuilder(org.dp.avro.MyKey.Builder other) {
    return new org.dp.avro.MyKey.Builder(other);
  }
  
  /** Creates a new MyKey RecordBuilder by copying an existing MyKey instance */
  public static org.dp.avro.MyKey.Builder newBuilder(org.dp.avro.MyKey other) {
    return new org.dp.avro.MyKey.Builder(other);
  }
  
  /**
   * RecordBuilder for MyKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MyKey>
    implements org.apache.avro.data.RecordBuilder<MyKey> {

    private java.lang.CharSequence key;

    /** Creates a new Builder */
    private Builder() {
      super(org.dp.avro.MyKey.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.dp.avro.MyKey.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing MyKey instance */
    private Builder(org.dp.avro.MyKey other) {
            super(org.dp.avro.MyKey.SCHEMA$);
      if (isValidValue(fields()[0], other.key)) {
        this.key = data().deepCopy(fields()[0].schema(), other.key);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'key' field */
    public java.lang.CharSequence getKey() {
      return key;
    }
    
    /** Sets the value of the 'key' field */
    public org.dp.avro.MyKey.Builder setKey(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.key = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'key' field has been set */
    public boolean hasKey() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'key' field */
    public org.dp.avro.MyKey.Builder clearKey() {
      key = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public MyKey build() {
      try {
        MyKey record = new MyKey();
        record.key = fieldSetFlags()[0] ? this.key : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
