/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.dp.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MyValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MyValue\",\"namespace\":\"org.dp.avro\",\"fields\":[{\"name\":\"value\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence value;

  /**
   * Default constructor.
   */
  public MyValue() {}

  /**
   * All-args constructor.
   */
  public MyValue(java.lang.CharSequence value) {
    this.value = value;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return value;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: value = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'value' field.
   */
  public java.lang.CharSequence getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.CharSequence value) {
    this.value = value;
  }

  /** Creates a new MyValue RecordBuilder */
  public static org.dp.avro.MyValue.Builder newBuilder() {
    return new org.dp.avro.MyValue.Builder();
  }
  
  /** Creates a new MyValue RecordBuilder by copying an existing Builder */
  public static org.dp.avro.MyValue.Builder newBuilder(org.dp.avro.MyValue.Builder other) {
    return new org.dp.avro.MyValue.Builder(other);
  }
  
  /** Creates a new MyValue RecordBuilder by copying an existing MyValue instance */
  public static org.dp.avro.MyValue.Builder newBuilder(org.dp.avro.MyValue other) {
    return new org.dp.avro.MyValue.Builder(other);
  }
  
  /**
   * RecordBuilder for MyValue instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MyValue>
    implements org.apache.avro.data.RecordBuilder<MyValue> {

    private java.lang.CharSequence value;

    /** Creates a new Builder */
    private Builder() {
      super(org.dp.avro.MyValue.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.dp.avro.MyValue.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing MyValue instance */
    private Builder(org.dp.avro.MyValue other) {
            super(org.dp.avro.MyValue.SCHEMA$);
      if (isValidValue(fields()[0], other.value)) {
        this.value = data().deepCopy(fields()[0].schema(), other.value);
        fieldSetFlags()[0] = true;
      }
    }

    /** Gets the value of the 'value' field */
    public java.lang.CharSequence getValue() {
      return value;
    }
    
    /** Sets the value of the 'value' field */
    public org.dp.avro.MyValue.Builder setValue(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.value = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'value' field has been set */
    public boolean hasValue() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'value' field */
    public org.dp.avro.MyValue.Builder clearValue() {
      value = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    public MyValue build() {
      try {
        MyValue record = new MyValue();
        record.value = fieldSetFlags()[0] ? this.value : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
